// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbhhumtpdfalgkhzirew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiaGh1bXRwZGZhbGdraHppcmV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjQ2MzYsImV4cCI6MjA2NjgwMDYzNn0.xPN8YcVsB_3zIv9tHOju5FuTD9ECLuasnBTVyGWwe88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});